-- Ajmal Esa
-- Question 1
-- Creat copy of henry.branch table
CREATE TABLE HENRYBRANCHCOPY SELECT * FROM HENRY.BRANCH;

-- Insert a value into the HENRYCOPY database
INSERT INTO HENRYBRANCHCOPY (BRANCH_NUM, BRANCH_NAME, BRANCH_LOCATION, NUM_EMPLOYEES)
VALUES ((SELECT MAX(BRANCH_NUM) + 2 FROM HENRY.BRANCH), 'Henry Westshore', 'Westshore Mall', 25);

-- Show all contents of branch copy for demonstration
SELECT * FROM HENRYBRANCHCOPY;


-- Question 2
-- CREATING COPY OF TABLES
CREATE TABLE HENRYAUTHORCOPY SELECT * FROM HENRY.AUTHOR;
CREATE TABLE HENRYBOOKCOPY SELECT * FROM HENRY.BOOK;
CREATE TABLE HENRYWROTECOPY SELECT * FROM HENRY.WROTE;
CREATE TABLE HENRYINVENTORYCOPY SELECT * FROM HENRY.INVENTORY;

-- INSERTING DATA INTO TABLES
INSERT INTO HENRYAUTHORCOPY 
VALUES ((SELECT MAX(AUTHOR_NUM)+ 1 FROM AUTHOR) , 'ESA', 'AJMAL');
INSERT INTO HENRYBOOKCOPY
VALUES ('0555', 'INTRO TO SQL', 444, 'EDU', 10.00, 'N');
INSERT INTO HENRYWROTECOPY  
VALUES ('0555', 26, 1);
INSERT INTO HENRYINVENTORYCOPY 
VALUES ('0555', 5, 1);

-- DEMO OF UPDATED TABLES
SELECT * FROM HENRYAUTHORCOPY;
SELECT * FROM HENRYBOOKCOPY;
SELECT * FROM HENRYWROTECOPY;
SELECT * FROM HENRYINVENTORYCOPY;


-- QUESTION 3
CREATE TABLE ORDERLINECOPY SELECT * FROM PREMIERE.ORDER_LINE;
CREATE TABLE CUSTOMERCOPY SELECT * FROM PREMIERE.CUSTOMER;
CREATE TABLE ORDERSCOPY SELECT * FROM PREMIERE.ORDERS;

INSERT INTO ORDERSCOPY 
VALUES (9539, '2007-10-21', 148);
INSERT INTO ORDERLINECOPY
VALUES 
	(9539, 'AT94', 11, 21.95),
	(9539, 'DR93', 1, 495.00),
    (9539, 'DW11', 1, 399.99);

SELECT * FROM ORDERLINECOPY;
SELECT * FROM CUSTOMERCOPY;
SELECT * FROM ORDERSCOPY;