-- Question 1
-- Creat copy of henry.branch table
CREATE TABLE HENRYBRANCHCOPY SELECT * FROM HENRY.BRANCH;

-- Insert a value into the HENRYCOPY database
INSERT INTO HENRYBRANCHCOPY (BRANCH_NUM, BRANCH_NAME, BRANCH_LOCATION, NUM_EMPLOYEES)
VALUES ((SELECT MAX(BRANCH_NUM) + 2 FROM HENRY.BRANCH), 'Henry Westshore', 'Westshore Mall', 25);

-- Show all contents of branch copy for demonstration
SELECT * FROM HENRYBRANCHCOPY;

-- Question 2
-- CREATING COPY OF TABLES
CREATE TABLE HENRYAUTHORCOPY SELECT * FROM HENRY.AUTHOR;
CREATE TABLE HENRYBOOKCOPY SELECT * FROM HENRY.BOOK;
CREATE TABLE HENRYWROTECOPY SELECT * FROM HENRY.WROTE;
CREATE TABLE HENRYINVENTORYCOPY SELECT * FROM HENRY.INVENTORY;

-- INSERTING DATA INTO TABLES
INSERT INTO HENRYAUTHORCOPY 
VALUES ((SELECT MAX(AUTHOR_NUM)+ 1 FROM AUTHOR) , 'ESA', 'AJMAL');
INSERT INTO HENRYBOOKCOPY
VALUES ('0555', 'INTRO TO SQL', 444, 'EDU', 10.00, 'N');
INSERT INTO HENRYWROTECOPY  
VALUES ('0555', 26, 1);
INSERT INTO HENRYINVENTORYCOPY 
VALUES ('0555', 5, 1);

-- DEMO OF UPDATED TABLES
SELECT * FROM HENRYAUTHORCOPY;
SELECT * FROM HENRYBOOKCOPY;
SELECT * FROM HENRYWROTECOPY;
SELECT * FROM HENRYINVENTORYCOPY;


-- QUESTION 3
